### ISSUE TITLE
Error resolving version for plugin 'com.unboundid.build:osslicense-maven-plugin'

### ISSUE THREAD

**Issue by jwilleke** [UnboundID/scim#12]
I know this maybe a lack of maven knowledge, but I have been trying to compile this for a while without any success.

I am on the latest version of OS X 10.11.6 (15G1004).

Running from the root base:
sudo mvn clean install

I always receive these errors:
Error resolving version for plugin 'com.unboundid.build:osslicense-maven-plugin' from the repositories [local (/var/root/.m2/repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository

and
The following artifacts could not be resolved: com.unboundid.product:ldapsdk:jar:3.1.1-se

and
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:javadoc (generate-javadoc) on project scim-ldap: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - /Volumes/ESSD1/git-willeke/scim/scim-ldap/target/generated-sources/jaxb2/com/unboundid/scim/ldap/AttributeDefinition.java:27: error: bad use of '>'

Can anyone provide assistance?

Thanks -jim

**Comment by richardcardona** [comment]
Jim,
We have a known issue open to track this issue. You can basically comment out the use of the osslicense-maven-plugin which is used to check for declared oss licenses. And the public artifact for the LDAP SDK is:
`<dependency>`
`    <groupId>com.unboundid</groupId>`
`    <artifactId>unboundid-ldapsdk</artifactId>`
`    <version>3.1.1</version>`
`</dependency>`

I've included a git patch attachment which you can apply to your build environment using git apply.

[scim11-public-build.patch.txt](https://github.com/UnboundID/scim/files/499305/scim11-public-build.patch.txt)

**Comment by jwilleke** [comment]
Thanks for the help.

I am using Java version: 1.8.0_101, vendor: Oracle Corporation

Now I get down to:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:javadoc (generate-javadoc) on project scim-ldap: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - /Volumes/ESSD1/git-willeke/scim/scim-ldap/target/generated-sources/jaxb2/com/unboundid/scim/ldap/AttributeDefinition.java:27: error: bad use of '>'
[ERROR] * &lt;complexType name="AttributeDefinition">

(repeated many times)

**Comment by richardcardona** [comment]
Javadoc is much stricter in Java SE 8 than previous version. The SCIM 1.1 SDK was developed on Java SE 7. To build on Java SE 8, skip the javadoc generation step with:
mvn -Dmaven.javadoc.skip=true install

If you need to build the Java docs, you'll need to build that on Java SE 7. Java SE 7 is still available from Oracle or you can use OpenJDK 7 on a linux system.

**Comment by jwilleke** [comment]
Thanks for all the help.

**Comment by bertold** [comment]
This has been addressed in the 1.8.15 release. The release will be pushed to Maven Central soon.
