### ISSUE TITLE
Cannot change endpoint

### ISSUE THREAD

**Issue by tmasselink** [UnboundID/scim#8]
I'm hitting a SCIM endpoint that is not standard(it uses lower case letters for user and group endpoints). So your API lets me specify the base url but not the endpoints my provider actually uses.

**Comment by richardcardona** [comment]
Instead of getting a UserEndpoint via SCIMService.getUserEndpoint() or getGroupEndpoint(), try using SCIMService.getEndpoint("user", UserResource.USER_RESOURCE_FACTORY) and SCIMService.getEndpoint("group", GroupResource.GROUP_RESOURCE_FACTORY).

**Comment by tmasselink** [comment]
final SCIMEndpoint<UserResource> endpoint = scimService.getEndpoint("user", UserResource.USER_RESOURCE_FACTORY);

Throws com.unboundid.scim.sdk.ResourceNotFoundException: Not Found

**Comment by richardcardona** [comment]
By requesting a custom endpoint the SCIM SDK issues a request for the endpoint resource descriptor, e.g. https://scim-server/base-uri?filter=endpoint+eq+"user". When that request returns a 404 response code you get the exception above.
