### ISSUE TITLE
Are things in the works to update to the schema for SCIM 2.0?

### ISSUE THREAD

**Issue by kentoj** [UnboundID/scim#9]
There are many more implementations of SCIM 1.1 than 2.0. The implementations listed [here](http://www.simplecloud.info/) show an Unbound product Data Broker using SCIM 2.0. 
Are there plans to take this local repository to SCIM2.0?

**Comment by richardcardona** [comment]
The UnboundID SCIM 2.0 implementation used by the Data Broker is available publicly here: https://github.com/unboundid/scim2

**Comment by kentoj** [comment]
Never mind, I found the new repo. Feel free to delete this.
